/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const __: typeof import('@/modules/useTranslations')['__']
  const _t: typeof import('@/modules/useTranslations')['_t']
  const getMeta: typeof import('@/utils/getMeta')['getMeta']
  const hasWindow: typeof import('@/utils/hasWindow')['hasWindow']
  const route: typeof import('ziggy-js')['route']
  const useTranslations: typeof import('@/modules/useTranslations')['useTranslations']
}
